otica/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from django.conf import settings                # import to work with static files
from django.conf.urls.static import static      # import to work with static files

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('oticas.urls', namespace='oticas')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # +... added to work with static files

oticas/urls.py
"""Define padrões de URL para oticas."""

from django.conf.urls import url
from . import views
from django.contrib.auth.views import login, logout

urlpatterns = [
    # Página inicial
    url(r'^$', views.index, name='index'),
    url(r'^oculos/$', views.oculos, name='oculos'),
    url(r'^login/$', login, {'template_name': 'oticas/login.html'}, name='login'),
    url(r'^logout/$', logout, {'template_name': 'oticas/logout.html'}, name='logout'),
    url(r'^cadastro/$', views.cadastro, name='cadastro'),
    url(r'^endereco/$', views.endereco, name='endereco'),
    url(r'^carrinho/$', views.carrinho, name='carrinho'),
    url(r'^comprar/$', views.comprar, name='comprar'),
    url(r'^contato/$', views.contato, name='contato'),
    url(r'^carrinho/(?P<oculos_id>\d+)/adicionar$', views.adicionaCarrinho, name='adicionar'),
    url(r'^carrinho/(?P<oculos_id>\d+)/deletar$', views.deletaCarrinho, name='deletar'),
]

oticas/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import EnderecoUser


class RegistroForm(UserCreationForm):

    email = forms.EmailField(label='E-mail', required=True)
    telefone = forms.CharField()
    cpf = forms.CharField(label='CPF')

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
            'telefone',
            'cpf',
        )
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control form-control-sm'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control form-control-sm'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control form-control-sm'}),
            'email': forms.EmailInput(attrs={'class': 'form-control form-control-sm'}),
        }

        labels = {
            'first_name': 'Nome',
            'last_name': 'Sobrenome',
            'cpf': 'CPF',
        }


    def save(self, commit=True):
        user = super(RegistroForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']
        user.telefone = self.cleaned_data['telefone']
        user.cpf = self.cleaned_data['cpf']

        if commit:
            user.save()

        return user


class EnderecoForm(forms.ModelForm):
    cep = forms.TextInput()
    rua = forms.TextInput()
    numero = forms.TextInput()
    complemento = forms.TextInput()
    bairro = forms.TextInput()
    cidade = forms.TextInput()
    estado = forms.TextInput()

    class Meta:
        model = EnderecoUser
        fields = (
            'cep',
            'rua',
            'numero',
            'complemento',
            'bairro',
            'cidade',
            'estado',
        )

        labels = {
            'cep': 'CEP',
            'rua': 'Rua',
            'numero': 'Número',
            'complemento': 'Complemento',
            'bairro': 'Bairro',
            'cidade': 'Cidade',
            'estado': 'Estado',
        }

        widgets = {
            'cep': forms.TextInput(attrs={'onblur': "pesquisacep(this.value);"}),
        }

    def save(self, commit=True):
        user = super(EnderecoForm, self).save(commit=False)
        user.cep = self.cleaned_data['cep']
        user.rua = self.cleaned_data['rua']
        user.numero = self.cleaned_data['numero']
        user.complemento = self.cleaned_data['complemento']
        user.bairro = self.cleaned_data['bairro']
        user.cidade = self.cleaned_data['cidade']
        user.estado = self.cleaned_data['estado']

        if commit:
            user.save()

        return user


class ContatoForm(forms.Form):

    nome = forms.CharField(label='Nome', required=True)
    email = forms.EmailField(label='Email')
    mensagem = forms.CharField(label='Mensagem', widget=forms.Textarea(), required=True)

    def __init__(self, *args, **kwargs):
        super(ContatoForm, self).__init__(*args, **kwargs)
        self.fields['nome'].widget.attrs['class'] = 'form-control form-control-sm'
        self.fields['nome'].widget.attrs['id'] = 'id_nome_contato'
        self.fields['nome'].widget.attrs['placeholder'] = 'Digite seu nome completo'
        self.fields['email'].widget.attrs['class'] = 'form-control form-control-sm'
        self.fields['email'].widget.attrs['placeholder'] = 'Digite seu email'
        self.fields['mensagem'].widget.attrs['class'] = 'form-control form-control-sm'
        self.fields['mensagem'].widget.attrs['placeholder'] = 'Escreva aqui sua mensagem...'


class CepForm(forms.Form):

    cep = forms.CharField(label='', required=True)

    def __init__(self, *args, **kwargs):
        super(CepForm, self).__init__(*args, **kwargs)
        self.fields['cep'].widget.attrs['class'] = 'form-control mr-0'
        self.fields['cep'].widget.attrs['placeholder'] = '_____-___'

oticas/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.db.models import Sum
from django.core.mail import send_mail
from django.conf import settings
from django.views import generic
from .forms import RegistroForm, EnderecoForm, ContatoForm, CepForm
from .models import Carrinho
from .models import Oculos
from .functions import calcular_frete, prazo_maior_ano
from urllib.request import Request, urlopen



# Create your views here.

def index(request):
    """A página inicial de Oticas"""
    return render(request, 'oticas/index.html')

def context(request): # Criado para enviar context ao base.html
    if request.user.is_authenticated():
        qtd_carrinho= request.user.carrinho_set.all().count()
        context = {
            'qtd_carrinho': qtd_carrinho,
        }

        return context
    else:
        if not request.session.session_key:
            request.session.create()
        key = request.session.session_key
        carrinho = Carrinho.objects.filter(dono_ano=key).count()
        context = {
            'qtd_carrinho': carrinho
        }

        return context

class ProductListView(generic.ListView):
    model = Oculos
    template_name = 'oticas/oculos.html'
    context_object_name = 'oculos'
    paginate_by = 9

oculos = ProductListView.as_view()


def cadastro(request):
    if request.method == 'POST':
        form = RegistroForm(request.POST)
        context = {'form': form}
        if form.is_valid():
            form.save()
            return redirect('oticas:login')
        else:
            return render(request, 'oticas/cadastro.html', context)
    else:
        form = RegistroForm()

        context = {'form': form}
        return render(request, 'oticas/cadastro.html', context)

@login_required
def endereco(request):

    if request.method == 'POST':
        end_form = EnderecoForm(request.POST)
        context = {'end_form': end_form}
        if end_form.is_valid():
            novo_end = end_form.save(commit=False)
            novo_end.user = request.user
            novo_end.save()
            return redirect('oticas:index')
        else:
            return render(request, 'oticas/endereco.html', context)
    else:
        end_form = EnderecoForm()

        context = {'end_form': end_form}
        return render(request, 'oticas/endereco.html', context)



def adicionaCarrinho(request, oculos_id):
    if request.user.is_authenticated():
        oculos = Oculos.objects.get(id=oculos_id)
        oculos_a_adicionar = Carrinho(produto=oculos, dono=request.user, valor_total=oculos.valor)
        oculos_a_adicionar.save()
    else:
        key = request.session.session_key
        if request.session.session_key:
            oculos = Oculos.objects.get(id=oculos_id)
            oculos_a_adicionar = Carrinho(produto=oculos, dono_ano=key, valor_total=oculos.valor)
            oculos_a_adicionar.save()
        else:
            oculos = Oculos.objects.get(id=oculos_id)
            request.session.create()
            oculos_a_adicionar = Carrinho(produto=oculos, dono_ano=key, valor_total=oculos.valor)
            oculos_a_adicionar.save()

    return redirect('oticas:oculos')


def carrinho(request):
    if request.user.is_authenticated():
        oculos = Carrinho.objects.filter(dono=request.user).order_by('data_adc')
        total = Carrinho.objects.filter(dono=request.user).aggregate(Sum('valor_total'))['valor_total__sum'] or 0.00


        def calcula_frete (cep_destino, cep_origem ='14407000', peso='2', tipo_frete='04014',
                           altura = '10', largura = '20', comprimento = '20'):

            url = 'http://ws.correios.com.br/calculador/CalcPrecoPrazo.aspx?'
            url += '&nCdEmpresa='
            url += '&sDsSenha='
            url += '&nCdServico=' + tipo_frete
            url += '&sCepOrigem=' + cep_origem
            url += '&sCepDestino=' + cep_destino
            url += '&nVlPeso=' + peso
            url += '&nCdFormato=1'
            url += '&nVlComprimento=' + comprimento
            url += '&nVlAltura=' + altura
            url += '&nVlLargura=' + largura
            url += '&nVlDiametro=0'
            url += '&sCdMaoPropria=n'
            url += '&nVlValorDeclarado=0'
            url += '&sCdAvisoRecebimento=n'
            url += '&StrRetorno=xml'
            url += '&nIndicaCalculo=3'

            return(url)

        def prazo_maior (request):
            if request.user.is_authenticated():
                carrinho = Carrinho.objects.filter(dono=request.user)
                if carrinho:
                    lista_prazo = []
                    for i in carrinho:
                        lista_prazo.append(i.prazo)

                    return (int(max(lista_prazo)))
                else:
                    return (0)

            else:
                key = request.session.session_key

                carrinho = Carrinho.objects.filter(dono_ano=key).order_by('data_adc')
                if carrinho:
                    lista_prazo = []
                    for i in carrinho:
                        lista_prazo.append(i.prazo)

                    return (int(max(lista_prazo)))

                else:
                    return (0)

        cep_destino = request.user.enderecouser_set.values()[0]['cep']
        url = calcula_frete(cep_destino)

        request1 = Request(url)
        result = urlopen(request1).read()

        result = result.decode('ISO-8859-1')
        find_valor = ('<Valor>')
        find_end_valor = ('</Valor>')
        pos_valor = result.index(find_valor)
        pos_end_valor = result.index(find_end_valor)

        find_prazo = ('<PrazoEntrega>')
        find_end_prazo = ('</PrazoEntrega>')
        pos_prazo = result.index(find_prazo)
        pos_end_prazo = result.index(find_end_prazo)

        valor = result[pos_valor + len(find_valor): pos_end_valor]
        prazo = int(result[pos_prazo + len(find_prazo): pos_end_prazo])

        prazo_maior_prod = prazo_maior(request)

        prazo += prazo_maior_prod

        valor_math = valor.replace(',', '.')
        valor_math = float(valor_math)

        if oculos.all().count() <= 0:
            contagem = 1
        else:
            contagem = oculos.all().count()
        valor_unit = valor_math / contagem
        valor_unit = round(valor_unit, 2)

        total_math = float(total)

        total_geral = round((total_math + valor_math),2)


        context = {
            'url': url,
            'valor': valor,
            'prazo': prazo,
            'oculos': oculos,
            'total': total,
            'valor_unit' : valor_unit,
            'total_geral': total_geral,
        }

        return render(request, 'oticas/carrinho.html', context)

    else:
        key = request.session.session_key

        oculos = Carrinho.objects.filter(dono_ano=key).order_by('data_adc')
        total = Carrinho.objects.filter(dono_ano=key).aggregate(Sum('valor_total'))['valor_total__sum'] or 0.00

        if request.method == 'POST':
            cep_form = CepForm(request.POST)
            if cep_form.is_valid():
                novo_cep = str(cep_form)

                find_value = ('value="')
                find_end_value = ('" /></td></tr>')
                pos_value = novo_cep.index(find_value)
                pos_end_value = novo_cep.index(find_end_value)

                value = novo_cep[pos_value + len(find_value): pos_end_value]
                novo_cep = value


                url = calcular_frete(novo_cep)

                request1 = Request(url)
                result = urlopen(request1).read()

                result = result.decode('ISO-8859-1')
                find_valor = ('<Valor>')
                find_end_valor = ('</Valor>')
                pos_valor = result.index(find_valor)
                pos_end_valor = result.index(find_end_valor)

                find_prazo = ('<PrazoEntrega>')
                find_end_prazo = ('</PrazoEntrega>')
                pos_prazo = result.index(find_prazo)
                pos_end_prazo = result.index(find_end_prazo)

                valor = result[pos_valor + len(find_valor): pos_end_valor]
                prazo = int(result[pos_prazo + len(find_prazo): pos_end_prazo])

                prazo_maior_prod = prazo_maior_ano(request)

                prazo += prazo_maior_prod

                valor_math = valor.replace(',', '.')
                valor_math = float(valor_math)

                valor_unit = valor_math / oculos.count()
                valor_unit = round(valor_unit, 2)

                total_math = float(total)

                total_geral = round((total_math + valor_math),2)

                cep_form = CepForm()

                request.session['valor_unit'] = valor_unit
                valor_unit_ano = request.session['valor_unit']
                print(valor_unit_ano)

                valid = True


                context = {
                    'oculos': oculos,
                    'total': total,
                    'novo_cep': novo_cep,
                    'url': url,
                    'valor': valor,
                    'prazo': prazo,
                    'total_geral': total_geral,
                    'cep_form' : cep_form,
                    'valor_unit' : valor_unit,
                    'valid' : valid,
                }

                return render(request, 'oticas/carrinho.html', context)

            else:
                cep_form = CepForm()
                context = {
                    'oculos': oculos,
                    'total': total,
                    'cep_form': cep_form,
                }

                return render(request, 'oticas/carrinho.html', context)

        else:
            cep_form = CepForm()
            context = {
                'oculos': oculos,
                'total': total,
                'cep_form' : cep_form,
            }

            return render(request, 'oticas/carrinho.html', context)

oticas/templates/oticas/base.html
<!DOCTYPE HTML>
<html lang="pt-BR">

	<head>
		<meta charset="utf-8">
		<title>Gui - Ótica</title>
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

		<!-- CSS -->
		{% load staticfiles %}
		<link rel="stylesheet" href="{% static 'oticas/css/fontawesome-all.css' %}">
		<link rel="stylesheet" href="{% static 'oticas/css/bootstrap.css' %}">
		<link rel="stylesheet" href="{% static 'oticas/css/estilo.css' %}">
		<link rel="shortcut icon" type="image/x-icon" href="{% static 'oticas/img/favicon.ico' %}">
	</head>

	<body>

		<!-- Facebook -->
		<div id="fb-root"></div>
			<script>(function(d, s, id) {
				var js, fjs = d.getElementsByTagName(s)[0];
				if (d.getElementById(id)) return;
				js = d.createElement(s); js.id = id;
				js.src = 'https://connect.facebook.net/pt_BR/sdk.js#xfbml=1&version=v2.12';
				fjs.parentNode.insertBefore(js, fjs);
				}(document, 'script', 'facebook-jssdk'));
			</script>

		<!-- Barra Social Topo-->
		<section class="social p-1">
			<div class="container">
				<div class="row">
					<div class="col-6 col-md-4">
						<div class="social-icon">
							<a href="https://www.facebook.com/guile.hm" target="_blank"><i class="fab fa-facebook-square"></i></a>
							<a href="https://www.instagram.com/guilehm/" target="_blank"><i class="fab fa-instagram"></i></a>
							<a href="https://github.com/Guilehm" target="_blank"><i class="fab fa-github"></i></a>
						</div>
					</div>
					<div class="col-6 col-md-4">
						<!-- welcome info -->
						{% if user.is_authenticated and user.first_name %}
								<span class="text-white">Olá, {{ user.first_name }}!</span>
							{% elif user.is_authenticated %}
								<span class="text-white">Olá, {{ user.username }}!</span>
							{% else %}
						{% endif %}
					</div>
					<div class="col-12 col-md-4">
						<a href="#"><i class="fa fa-phone"></i>(16) 99999-9410</a>
						<a href="#"><i class="fa fa-envelope"></i>guile.hm@hotmail.com</a>

					</div>
				</div>
			</div>
		</section>

		<!-- Menu Principal -->
		<div class="container-fluid bg-light">
			<div class="container py-3">
				<nav class="navbar navbar-expand-sm navbar-light bg-light p-0">
					<a class="navbar-brand" href="#">
						<img src="{% static 'oticas/img/logo-01.png' %}" width="30" height="30" alt="">
						Ótica
					</a>

					<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
						<span class="navbar-toggler-icon"></span>
					</button>
					{% block menu %}
					<div class="collapse navbar-collapse" id="navbarNav">
						<ul class="navbar-nav ml-auto">
							<li class="nav-item active">
								<a class="btn btn-outline-dark btn-sm m-1" href="{% url 'oticas:index' %}">Home <span class="sr-only">(current)</span></a>
							</li>
							<li class="nav-item">
								<a class="btn btn-outline-dark btn-sm m-1" href="{% url 'oticas:oculos' %}">Produtos</a>
							</li>
							<li class="nav-item">
								<a class="btn btn-outline-dark btn-sm m-1" href="{% url 'oticas:contato' %}">Contato</a>
							</li>
							<li class="nav-item">
								<a class="btn btn-outline-primary btn-sm m-1" href="{% url 'oticas:carrinho' %}">Carrinho
									{% if qtd_carrinho %}
										<span class="badge badge-success">{{ qtd_carrinho }}</span>
									{% endif %}</a>
							</li>
							{% if user.is_authenticated %}
							<li class="nav-item">
								<a class="btn btn-outline-danger btn-sm m-1" href="{% url 'oticas:logout' %}">Log-out</a>
							</li>

							{% else %}
							<li class="nav-item">
								<a class="btn btn-outline-info btn-sm m-1" href="{% url 'oticas:login' %}">Log-in</a>
							</li>

							<li class="nav-item">
								<a class="btn btn-outline-success btn-sm m-1" href="{% url 'oticas:cadastro' %}">Cadastro</a>
							</li>
							{% endif %}
						</ul>
					</div>
					{% endblock menu %}
				</nav>
			</div>
		</div>

		<!-- Main view -->
		{% block main-view %}
		<div class="container-fluid">
			<div class="row">
				<div class="col-md-12 img-home">
					<!-- <h1 class="display-2 mt-4 title-black shadowed"><img class="logo-home" src="{% static 'oticas/img/logo-01.png' %}"></h1> -->
					<h1 class="display-3 mt-4 shadowed">Bem-vindo ao nosso site</h1>
					<!-- <p class="lead mx-4 mt-5">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur ut lobortis arcu. -->
					</p>
					<div class="text-center mt-4">
						<a role="button" class="btn btn-success btn-lg btn-center" href="{% url 'oticas:oculos' %}">Compre Agora</a>
					</div>
				</div>
			</div>
		</div>
		{% endblock main-view %}

        {% block content %}
        {% endblock content %}

		<!-- fale-conosco -->
		<section class="m-0">
			<div class="container-fluid fale-conosco bg-info text-center p-5">
				<div>
					<a href="{% url 'oticas:contato' %}">FALE CONOSCO</a>
				</div>
			</div>
		</section>

		<!-- Redes Sociais -->
		<section>
			<div class="container redes-sociais text-center">
				<div class="jumbotron bg-black">
					<h2 class="redes-texto" id="texto-redes">REDES SOCIAIS</h2>
					<div class="row">
						<div class="social-icon mt-5">
							<a href="https://www.facebook.com/guile.hm" class="p-5"><i class="fab fa-facebook-square a-incr"></i></i></a>
							<a href="https://www.instagram.com/guilehm/" class="p-5"><i class="fab fa-instagram a-incr"></i></a>
							<a href="https://github.com/Guilehm" class="p-5"><i class="fab fa-github a-incr"></i></a>
							<a href="https://www.linkedin.com/in/guils/" class="p-5"><i class="fab fa-linkedin a-incr"></i></a>
							<a href="https://twitter.com/Guile_hm" class="p-5"><i class="fab fa-twitter-square a-incr"></i></a>
						</div>
					</div>
				</div>
			</div>
		</section>

		<!-- visite nossas lojas -->
		<section class="m-0">
			<div class="container-fluid visite bg-light text-center p-5">
				<div>
					<a href="#">VISITE-NOS</a>
					<hr class="bg-white my-3">
				</div>

				<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3656.6107753607753!2d-46.632357184260364!3d-23.582418668257155!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x94ce597fa810fd37%3A0xdd4daf819f42b277!2sRua+Dona+In%C3%A1cia+Uchoa%2C+620+-+Vila+Mariana%2C+S%C3%A3o+Paulo+-+SP%2C+04110-021!5e0!3m2!1spt-BR!2sbr!4v1518553737928"
					width="100%" height="400px" frameborder="0" style="border:0" allowfullscreen>
				</iframe>

			</div>
		</section>

		<!--Footer-->
		<footer>
			<div class="container-fluid bg-dark pt-3">
				<div class="container text-white">
					<div class="row">
						<div class="class col-6 pl-0 pr-0">
							<p>Copyright © 2018. Ótica. Todos os direitos reservados. </p>
						</div>
						<div class="col-6 linkf">
							<p>Desenvolvido em Python por
							<a href="https://www.facebook.com/guile.hm">Guilherme Luis</a>.</p>
						</div>
					</div>
				</div>
			</div>
		</footer>

		<!-- Optional JavaScript -->
		<!-- jQuery first, then Popper.js, then Bootstrap JS -->
		<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

	</body>
</html>

oticas/templates/oticas/cadastro.html
{% extends "oticas/base.html" %}
{% load staticfiles %}

{% block main-view %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12 img-banner4">
        </div>
    </div>
</div>
{% endblock main-view %}

{% block content %}

<div class="container my-5">
    <form method="POST">
        <h2 class="display-4">Cadastre-se</h2>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-sm btn-outline-success">Cadastrar</button>
    </form>
</div>

{% endblock content %}

oticas/templates/oticas/comprar.html
{% extends "oticas/base.html" %}
{% load staticfiles %}

{% block main-view %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <h2 class="text-center mx-4 mt-5 text-dark">
                Redirecionando ao site do PayPal...
            </h2>
        </div>
    </div>
</div>
{% endblock main-view %}

{% block content %}
<!-- carrinho -->

<div class="container">

    <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_self">
        <input type="hidden" name="cmd" value="_cart">
        <input type="hidden" name="upload" value="1">
        <input type="hidden" name="business" value="guile.hm@hotmail.com">
        <input type="hidden" name="currency_code" value="BRL">
        <input type="hidden" name="lc" value="BR">

        {% for i in oculos %}
        <input type="hidden" name="item_name_{{ forloop.counter }}" value="{{ i }}">
        <input type="hidden" name="amount_{{ forloop.counter }}" value="{{ i.valor }}">
        <input type="hidden" name="shipping_{{ forloop.counter }}" value="{{ valor_unit }}">
        {% endfor %}

        <input type="image" id="paypalform" src="" name="submit"
               alt="" target="_self">
    </form>

</div>

<div class="container">
    <!-- working form -->


</div>
<script>
    window.onload = function() {
			document.getElementById('paypalform').click();
		}
</script>

{% endblock content %}

oticas/templates/oticas/contato.html
{% extends "oticas/base.html" %}
{% load staticfiles %}

{% block main-view %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12 img-banner3">
        </div>
    </div>
</div>
{% endblock main-view %}

{% block content %}

<div class="container my-5">
    {% if sucesso %}
    <div class="alert alert-success">
        Mensagem enviada com sucesso
    </div>
    {% endif %}
    <form method="POST">
        <h2 class="display-4">Entre em contato conosco</h2>
        {% csrf_token %}
        {{ contato_form.as_p }}
        <button type="submit" class="btn btn-sm btn-outline-success">Enviar</button>
    </form>
</div>

{% endblock content %}

oticas/templates/oticas/endereco.html
{% extends "oticas/base.html" %}
{% load staticfiles %}

{% block main-view%}
<script src="{% static 'oticas/js/cep.js' %}"></script>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12 img-home">
            <h1 class="display-2 mt-4 title-white shadowed">Endereço</h1>
            <p class="lead mx-4 mt-5">Cadastre seu endereço de entrega para comprar em nosso site.
            </p>
            <div class="text-center mt-4">
                <a role="button" class="btn btn-info btn-lg btn-center" href="#">Editar Endereço</a>
            </div>
        </div>
    </div>
</div>
{% endblock main-view %}

{% block content %}

<div class="container my-5">
    <form method="POST">
        <h2 class="display-4">Cadastre seu endereço</h2>
        {% csrf_token %}
        {{ end_form.as_p }}
        <button type="submit" class="btn btn-sm btn-outline-success">Salvar</button>
    </form>
</div>


{% endblock content %}

oticas/templates/oticas/login.html
{% extends "oticas/base.html" %}
{% load staticfiles %}

{% block main-view %}
{% endblock main-view %}

{% block content %}

<div class="container my-5">
    <form method="post">
        <h2 class="display-4">Login</h2>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-sm btn-outline-success">Login</button>
    </form>
    <br>
    <h6 class="text-muted">Caso ainda não tenha um conta, cadastre-se através deste <a href="{% url 'oticas:cadastro' %}">link</a></h6>
</div>

{% endblock content %}

oticas/templates/oticas/logout.html
{% extends "oticas/base.html" %}
{% load staticfiles %}

{% block main-view%}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12 img-home">
            <h1 class="display-3 mt-4 title-white shadowed">Você fez o Logout</h1>
            <div class="text-center mt-4">
                <a role="button" class="btn btn-success btn-lg btn-center" href="">Desconectado com sucesso</a>
            </div>
        </div>
    </div>
</div>
{% endblock main-view %}

{% block content %}

<div class="container my-5">

</div>

{% endblock content %}